services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"           # 将宿主机80端口映射到容器80端口
      - "443:443"
    volumes:
      - ./conf/nginx:/etc/nginx:ro  # 挂载自定义配置
      - ./www:/usr/share/nginx/html:ro        # 挂载网页内容
    restart: always
    networks:
      - niu-network

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - niu-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./data/backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./.env
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://root:${MONGODB_ROOT_PASSWORD}@mongodb:27017
      - PORT=3001
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./conf/backend:/app/config:ro
    networks:
      - niu-network

networks:
  niu-network:
    driver: bridge

volumes:
  mongo-data: