server {
    listen 80;
    server_name xiaoniu.tech www.xiaoniu.tech;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name xiaoniu.tech www.xiaoniu.tech;

    ssl_certificate     /etc/letsencrypt/live/xiaoniu.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xiaoniu.tech/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;

    location ^~ /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
        allow all;
    }

    location ~ /\. {
        deny all;
    }

    include /etc/nginx/conf.d/*.location;
}