server {
    listen 80;
    server_name localhost;
    resolver 8.8.8.8 valid=300s;
    root /usr/share/nginx/html;

    # 防止访问隐藏文件喵
    location ~ /\. {
        deny all;
    }

    include /etc/nginx/conf.d/*.location;
}