import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react';

const APP_LOCALE_KEY = 'app_locale';
const APP_THEME_KEY = 'app_theme';
const DEFAULT_LOCALE = 'zh-CN';
const DEFAULT_THEME = 'dark';
const THEME_TRANSITION_DURATION_MS = 1000;
const THEME_TRANSITION_SETTLE_MS = 120;
const THEME_TRANSITION_FALLBACK_MS = THEME_TRANSITION_DURATION_MS + 800;
const THEME_TRANSITION_PROPERTIES = ['background-color', 'border-color', 'box-shadow', 'color', 'fill', 'opacity', 'stroke', 'text-decoration-color'];

const LOCALE_OPTIONS = [
  { code: 'zh-CN', shortLabel: '简', label: '简体中文' },
  { code: 'zh-TW', shortLabel: '繁', label: '繁體中文' },
  { code: 'en-US', shortLabel: 'EN', label: 'English' },
];

const DICTIONARIES = {
  'zh-CN': {
    common: {
      siteName: 'XiaoNiu Tech',
      blogName: 'XN Blog',
      chatName: 'XN Chat',
      loading: '加载中...',
      cancel: '取消',
      close: '关闭',
      confirm: '确认',
      save: '保存',
      saving: '保存中...',
      back: '返回',
      backHome: '返回主页',
      previousPage: '上一页',
      nextPage: '下一页',
      clear: '清除',
      search: '搜索',
      login: '登录',
      register: '注册',
      loginOrRegister: '登录/注册',
      logout: '登出',
      lightMode: '浅色',
      darkMode: '深色',
      guestMode: '游客模式',
      upload: '上传',
      retry: '重试',
      draft: '草稿',
      deleted: '已删除',
      settings: '设置',
      edit: '编辑',
      delete: '删除',
      restore: '恢复',
      permanentDelete: '永久删除',
      manage: '管理',
      create: '创建',
      open: '打开',
      email: '邮箱',
      password: '密码',
      nickname: '昵称',
      bio: '简介',
      language: '语言',
      theme: '主题',
      words: '字',
      articles: '篇文章',
      comments: '评论',
      likes: '赞',
      views: '阅读',
      untitledChat: '新对话',
      assistantName: 'AI 助手',
      agentName: '智能体',
      agentConversation: '智能体对话',
    },
    time: {
      justNow: '刚刚',
      minutesAgo: '{count} 分钟前',
      hoursAgo: '{count} 小时前',
      daysAgo: '{count} 天前',
    },
    home: {
      eyebrow: '个人轨道',
      heroTitle: 'XiaoNiu Tech',
      heroSubtitle: '把我的聊天实验、技术文章和常用入口整理到同一个个人站点。',
      actionChat: 'Chat',
      actionBlog: '博客',
      actionGithub: 'Github',
      featureChatTitle: 'Chat Lab',
      featureChatDesc: '多模型聊天、智能体会话与工作流实验。',
      featureBlogTitle: '技术博客',
      featureBlogDesc: '工程记录、经验总结与长期写作。',
      featureGithubTitle: 'Github 仓库',
      featureGithubDesc: '开源项目、脚本工具和代码试验。',
      featureGamesTitle: '小游戏',
      featureGamesDesc: '轻量交互原型与设计练习。',
      featureTagProduct: 'Product Surface',
      featureTagWriting: 'Writing',
      featureTagCode: 'Codebase',
      featureTagSandbox: 'Sandbox',
      open: 'Open',
      navTitle: 'XiaoNiu Tech',
      navLogin: '登录',
      navRegister: '注册',
      navTheme: '切换主题',
      navLanguage: '切换语言',
      heroKicker: 'Digital Workspace',
      heroSummaryLead: '从 AI 对话到技术写作，所有入口在同一张首页中完成编排。',
      heroSummaryBody: '更轻的导航、更少的噪音，以及为长期迭代预留的清晰结构。',
      orbitCardHint: '点击轨道生成彗星，悬浮时会出现粒子效果。',
      orbitSunTitle: '点击太阳触发超新星',
      statusTitle: '现在可用',
      statusOneLabel: 'Chat',
      statusOneValue: '多模型流式会话',
      statusTwoLabel: 'Blog',
      statusTwoValue: '写作与发布',
      statusThreeLabel: 'Profile',
      statusThreeValue: '设置与头像管理',
      footerBuiltBy: 'BUILT BY LITTLEFOGCAT',
      footerEmail: '邮箱',
      footerGithub: 'GitHub',
      footerQQ: 'QQ',
      footerWechat: '微信',
      footerWechatQrAlt: '微信二维码',
    },
    placeholder: {
      comingSoon: '即将开放',
      backHome: '返回首页',
      enterChat: '进入 Chat',
      gamesTitle: '小游戏',
      gamesDescription: '暂未开放，敬请期待。',
    },
    login: {
      pageTitle: '登录 - XN',
      title: 'XiaoNiu Tech',
      welcomeBack: '欢迎回来，请登录',
      registerIntro: '注册新账号并完成邮箱验证',
      loginTab: '登录',
      registerTab: '注册',
      emailPlaceholder: '请输入邮箱',
      passwordPlaceholder: '请输入密码',
      newPasswordPlaceholder: '请设置密码，至少 8 位',
      loginLoading: '登录中...',
      guestAccess: '游客访问',
      captchaTitle: '人机验证',
      captchaDescription: '请回答下面的算术题',
      captchaLoading: '验证码加载中...',
      captchaRefresh: '刷新题目',
      captchaAnswerPlaceholder: '输入答案',
      sendCode: '发送验证码',
      sendCodeLoading: '发送中...',
      codePlaceholder: '请输入邮箱验证码',
      verifyAndLogin: '验证并登录',
      verifyLoading: '验证中...',
      resendIn: '{seconds} 秒后可重新发送',
      switchToLogin: '返回登录',
      back: '返回',
      loadCaptchaFailed: '加载人机验证失败',
      loginFailed: '登录失败，请重试',
      sendCodeFailed: '发送验证码失败',
      verifyFailed: '验证失败，请重试',
      codeSentNotice: '验证码已发送至 {email}，10 分钟内有效。',
      codeResendNotice: '{seconds} 秒后可重新发送。',
    },
    blog: {
      pageTitle: 'XN Blog',
      searchPlaceholder: '搜索文章...',
      backHomeTitle: '返回主页',
      managePosts: '管理文章',
      createMenu: '创作',
      createPost: '写博客',
      importPosts: '导入文章',
      settings: '设置',
      logout: '登出',
      importTitle: '导入文章',
      importHint: '仅支持导入 .md 文件。你可以一次选择多个 Markdown 文件，或直接选择一个文件夹批量导入。',
      selectFiles: '选择文件',
      selectFolder: '选择文件夹',
      importing: '导入中...',
      importNothing: '未能导入任何文章',
      importSummarySuccess: '成功导入 {count} 篇文章草稿。',
      importSummaryFailed: '失败 {count} 篇。',
      importFirstError: '首个错误：{message}',
      tagFilter: '标签：',
      noPosts: '暂无文章',
      noMatchedPosts: '未找到匹配的文章',
      readCount: '{count} 阅读',
      likeCount: '{count} 赞',
      commentCount: '{count} 评论',
      readCountLong: '{count} 次阅读',
      likeCountLong: '{count} 次点赞',
      backToBlog: '返回博客首页',
      postNotFound: '文章不存在',
      postMissing: '该文章未找到或已被删除',
      liked: '已赞',
      like: '点赞',
      editPost: '编辑文章',
      commentsTitle: '评论 ({count})',
      commentPlaceholder: '写下你的评论...',
      submitComment: '发表评论',
      commentSubmitting: '提交中...',
      loginToComment: '登录后即可发表评论',
      noComments: '暂无评论',
      sidebarIntro: '全栈开发者，专注于 Web 技术与 AI 应用。',
      totalWords: '总字数',
      tagCollection: '标签合集',
      noTags: '暂无标签',
      editorTitlePlaceholder: '文章标题...',
      editorTagsPlaceholder: '标签，用逗号分隔...',
      editorContentPlaceholder: '使用 Markdown 编写内容...',
      editorPreview: '预览',
      editorEmptyPreview: '*暂无内容*',
      saveDraft: '存草稿',
      publishing: '发布中...',
      publish: '发布',
      saveFailed: '保存失败，请稍后重试。',
      unpublish: '撤回',
      writePageTitle: '写博客 - XN Blog',
      editPageTitle: '编辑: {title} - XN Blog',
      managePageTitle: '文章管理 - XN Blog',
      userNotFound: '用户不存在',
      articlesTitle: '文章',
      articleCount: '{count} 篇文章',
      wordCount: '{count} 字',
      mixedStats: '{views} 阅读 · {likes} 赞 · {comments} 评论',
      myPosts: '我的文章 ({count})',
      trashBin: '垃圾桶 ({count})',
      batchModeOn: '批量管理',
      batchModeOff: '完成批量管理',
      selectAllCurrent: '全选当前列表',
      selectedCount: '已选 {count} 篇',
      clearSelection: '清空选择',
      bulkPublish: '批量发布',
      bulkUnpublish: '批量撤回',
      bulkDelete: '批量删除',
      bulkRestore: '批量恢复',
      bulkPermanentDelete: '批量永久删除',
      trashEmpty: '垃圾桶为空',
      deletedAt: '删除于 {date}',
      bulkActionFailed: '批量操作失败',
      trashConfirmOne: '确定要删除这篇文章吗？它将移入垃圾桶。',
      trashConfirmMany: '确定要将选中的 {count} 篇文章移入垃圾桶吗？',
      permanentDeleteConfirmOne: '此操作不可撤销，确定要永久删除这篇文章及其所有评论吗？',
      permanentDeleteConfirmMany: '此操作不可撤销，确定要永久删除选中的 {count} 篇文章及其评论吗？',
      emptyDelete: '未选择要删除的文章。',
      emptyRestore: '未选择要恢复的文章。',
      emptyPermanentDelete: '未选择要永久删除的文章。',
      emptyDraftPublish: '请选择至少一篇草稿文章。',
      emptyPublishedUnpublish: '请选择至少一篇已发布文章。',
      movedToTrash: '已将 {count} 篇文章移入垃圾桶。',
      restoredPosts: '已恢复 {count} 篇文章。',
      permanentlyDeleted: '已永久删除 {count} 篇文章。',
      publishedPosts: '已发布 {count} 篇文章。',
      unpublishedPosts: '已将 {count} 篇文章撤回为草稿。',
      profileLoadingFailed: '加载用户信息失败',
    },
    stock: {
      listPageTitle: '股市复盘 - XiaoNiu Tech',
      listDescription: '按日期回顾热点板块、消息面与次日关注方向。',
      heroEyebrow: 'Stock Review',
      heroTitle: '股市复盘',
      heroSubtitle: '把盘后观察整理成结构化记录，方便复查热点、消息和明日关注线索。',
      statsTotal: '记录数',
      statsCurrentPage: '当前页',
      statsLatestDate: '最新日期',
      noPermission: '当前账号没有股市复盘查看权限',
      noCreatePermission: '当前账号没有创建股市复盘的权限',
      noUpdatePermission: '当前账号没有编辑股市复盘的权限',
      loadProfileFailed: '加载用户信息失败',
      loadListFailed: '加载复盘列表失败',
      loadDetailFailed: '加载复盘详情失败',
      filtersTitle: '筛选条件',
      filtersDescription: '按关键词、日期和板块快速定位复盘记录。',
      searchPlaceholder: '搜索标题、板块、个股或理由',
      sectorPlaceholder: '板块关键词',
      allImpactLevels: '全部影响级别',
      impactPositive: '利好',
      impactNegative: '利空',
      impactNeutral: '中性',
      applyFilters: '应用筛选',
      resetFilters: '重置',
      createReview: '新建复盘',
      listTitle: '复盘列表',
      listDescriptionShort: '按日期倒序展示摘要，点击进入完整详情。',
      loadingList: '正在加载复盘列表...',
      noReviews: '当前筛选条件下暂无复盘记录',
      articleTitle: '{date} 复盘',
      newsCount: '{count} 条消息',
      summaryFromFocus: '关注方向',
      summaryFromHot: '热点概览',
      emptySummary: '暂无摘要，点击查看完整内容。',
      timeUnknown: '未标注时间',
      detailPageTitle: '{date} 股市复盘 - XiaoNiu Tech',
      detailDescription: '查看单日股市复盘的完整详情。',
      detailTitle: '复盘详情',
      editorCreateTitle: '新建股市复盘 - XiaoNiu Tech',
      editorEditTitle: '编辑股市复盘 - XiaoNiu Tech',
      editorDescription: '维护当日热点、消息面、关注板块与明日关注个股。',
      createMode: '新建复盘',
      editMode: '编辑复盘',
      articleLead: '围绕当日行情脉络整理盘后结论，为次日复查和盘前准备提供统一入口。',
      backToList: '返回列表',
      emptyDetail: '未找到对应复盘记录。',
      created: '复盘已创建',
      updated: '复盘已更新',
      saveFailed: '保存复盘失败',
      deleteConfirm: '确定要删除当前复盘记录吗？此操作不可撤销。',
      deleteFailed: '删除复盘失败',
      editorDateEyebrow: 'Header',
      editorDateTitle: '复盘日期',
      editorDateDescription: '默认带入当天日期；如有需要，可创建同一天的多条复盘记录。',
      marketsEyebrow: 'Market Overview',
      marketsTitle: '市场总览',
      marketsDescription: '维护市场摘要、指数表现与量能描述。',
      fieldMarketSummary: '市场摘要',
      fieldMarketVolume: '量能描述',
      indicesTitle: '指数列表',
      sectionIndexItem: '指数 {index}',
      fieldIndexCode: '指数代码',
      fieldIndexName: '指数名称',
      fieldClosePrice: '收盘价',
      topSectorsEyebrow: 'Top Sectors',
      topSectorsTitle: '今日热点',
      topSectorsDescription: '记录行业板块、概念板块、领跌板块与热点总结。',
      conceptsTitle: '热点概念',
      fallingSectorsTitle: '领跌板块',
      todayHotSummaryLabel: '热点总结',
      sectionHotItem: '热点 {index}',
      removeItem: '删除',
      addItem: '新增一项',
      fieldSectorName: '板块名称',
      fieldChangePercent: '涨幅，例如 3.5',
      fieldTopStocks: '每行一条：代码 | 名称 | 涨跌幅',
      newsEyebrow: 'Market News',
      newsTitle: '消息面',
      newsDescription: '按分类整理消息面，每行录入一条 markdown 内容。',
      sectionNewsItem: '消息 {index}',
      fieldNewsTitle: '标题',
      fieldNewsSummary: '摘要',
      fieldNewsDetail: '每行一条 markdown 内容',
      fieldNewsSource: '来源，可选',
      fieldPublishTime: 'YYYY-MM-DD HH:mm:ss',
      fieldImpactSectors: '受影响板块，使用逗号分隔',
      focusSectorsEyebrow: 'Sectors To Watch',
      focusSectorsTitle: '关注板块',
      focusSectorsDescription: '记录次日重点观察或继续持有的方向。',
      sectionFocusSectorItem: '关注板块 {index}',
      fieldReason: '关注理由',
      focusStocksEyebrow: 'Stocks To Watch',
      focusStocksTitle: '明日关注个股',
      focusStocksDescription: '按板块整理次日关注个股，每行一条：代码 | 名称 | 理由。',
      sectionFocusStockItem: '个股分组 {index}',
      fieldFocusStocksLines: '每行一条：代码 | 名称 | 理由',
      fieldStockCode: '股票代码',
      fieldStockName: '股票名称',
      noTopSectors: '暂无热点板块记录',
      topStocksLabel: '领涨股代码',
      noNews: '暂无消息面记录',
      sourceUnknown: '来源未标注',
      noFocusSectors: '暂无关注板块',
      noFocusStocks: '暂无关注个股',
    },
    settings: {
      pageTitle: '用户设置 - XN Blog',
      profileLoadingFailed: '加载用户信息失败',
      avatarUpdated: '头像已更新',
      avatarSaveFailed: '头像保存失败：{message}',
      currentPasswordRequired: '修改密码需要输入当前密码',
      saveSuccess: '保存成功',
      saveSuccessHint: '个人资料已更新。关闭提示后将返回上一页。',
      avatar: '头像',
      emailReadonly: '邮箱不可更改',
      nicknamePlaceholder: '设置昵称',
      bioPlaceholder: '写一段个人简介...',
      currentPasswordPlaceholder: '如需修改密码，请输入当前密码',
      newPasswordPlaceholder: '输入新密码（至少 8 位字符）',
      saving: '保存中...',
      cancel: '取消',
      backPrevious: '返回前页',
      title: '用户设置',
    },
    avatar: {
      chooseFile: '请选择文件',
      unsupportedType: '不支持的文件类型，仅允许 JPEG、PNG、GIF、WebP',
      unsupportedFormat: '不支持的图片格式',
      fileTooLarge: '文件过大（{size}MB），上限为 5MB',
      imageProcessFailed: '图片处理失败',
      imageLoadFailed: '图片加载失败',
      uploadFailed: '上传失败',
      avatarAlt: '头像',
      uploadAvatar: '上传头像',
      changeAvatar: '更换头像',
      clickToUpload: '点击上传头像',
      clickToEdit: '点击修改头像',
      modalTitle: '修改头像',
      previewAlt: '预览',
      currentAvatarAlt: '当前头像',
      reselect: '重新选择',
      selectImage: '选择图片',
      supportHint: '支持 JPEG / PNG / GIF / WebP，最大 5MB，长边自动缩放至 1024px',
      uploading: '上传中...',
      confirm: '确认',
    },
    chat: {
      pageTitle: 'XN Chat',
      selectIdentityTitle: '选择智能体 | XN Chat',
      currentSession: '当前会话：{name}',
      currentCompact: '当前：{name}',
      workspaceTitle: '聊天记录',
      workspaceLabel: 'Workspace',
      newChat: '新建聊天',
      openHistory: '打开聊天记录',
      closeHistory: '关闭聊天记录',
      emptyChats: '还没有会话，先开始一段新的对话。',
      deleteChat: '删除会话',
      expandSidebar: '展开侧边栏',
      collapseSidebar: '收起侧边栏',
      multiModelWorkbench: '多模型对话工作台',
      streamWorkbench: '多模型流式聊天工作台',
      addAgent: '添加智能体',
      openActions: '打开操作菜单',
      actionsLabel: 'Actions',
      actionsTitle: '聊天操作',
      backBottom: '回到底部',
      loadFailed: '加载失败',
      loadingModels: '加载中...',
      linkedAgent: 'Agent Linked',
      startConversationWith: '和 {name} 开始一段新对话',
      linkedAgentDescription: '这个智能体已经绑定到当前会话，发送第一条消息后，对话会自动切换到底部输入模式。',
      neuralConsole: 'Neural Console',
      heroTitle: '在这里开始下一段高效对话',
      heroDesc: '支持多模型、流式回复和智能体人设。',
      badgeStreaming: '流式回复',
      badgeMobile: '移动端适配',
      badgeIdentity: '智能体绑定',
      guestLimitCreate: '游客聊天记录已达到 {limit} 条上限，请登录后继续创建新会话。',
      guestLimitContinue: '游客聊天记录已达到 {limit} 条上限，请登录后继续。',
      modelPlaceholder: '选择模型',
      authLoginTitle: '返回登录页',
      authLogoutTitle: '登出',
      identityLab: 'Identity Lab',
      chooseAgentStart: '选择一个智能体开始对话',
      identityLabDesc: '智能体由服务端读取人格设定文件生成。每个智能体最多绑定一个会话，已存在的会话不会重复创建。',
      backToChat: '返回聊天',
      noIdentityAvailable: '暂无可用智能体，请在服务端配置 identities 目录后重试。',
      agentIndex: 'Agent {index}',
      identityUsed: '已存在会话',
      noDescription: '暂无描述',
      identityBinding: '绑定形式：单智能体单会话',
      enterConversation: '进入对话',
      createConversation: '创建对话',
      assistantRole: 'Assistant',
      meRole: 'Me',
      thinking: '正在思考',
      reasoningSummary: '已思考（用时 {seconds} 秒）',
      showReasoning: '显示思考过程',
      hideReasoning: '隐藏思考过程',
      copy: '复制',
      copied: '已复制',
      regenerate: '重新生成',
      messagePlaceholder: '发送消息...',
      importantNotice: 'AI 可能会产生错误信息，请核实重要内容',
      errorPrefix: '错误: {message}',
      assistantAvatarAlt: '{name} 头像',
      assistantFallbackAvatarAlt: '{name} 默认头像',
    },
    chatManage: {
      pageTitle: '聊天管理',
      chatModule: 'Chat Module',
      modelConfig: '模型配置',
      agentConfig: '智能体配置',
      newModel: '新建模型',
      newAgent: '新建智能体',
      modelProvider: '提供商',
      modelId: '模型 ID',
      modelDisplayName: '显示名称',
      modelInputType: '输入类型（逗号分隔）',
      modelContextWindow: '上下文窗口',
      modelMaxTokens: '最大输出 Token',
      providerConfig: '提供商请求配置（providerConfig）',
      compatConfig: '兼容扩展参数（compat）',
      saveModel: '保存模型',
      deleteModel: '删除模型',
      deleteModelConfirm: '确定删除模型"{name}"吗？',
      copyModel: '复制模型',
      modelCopied: '模型已复制',
      modelCreated: '模型配置已创建',
      modelUpdated: '模型配置已更新',
      modelDeleted: '模型配置已删除',
      agentId: '智能体 ID（创建后不可修改）',
      agentName: '名称',
      agentRole: '角色标签',
      agentAvatar: '头像',
      agentAvatarUrl: '头像 URL',
      agentDescription: '简介',
      agentSystemPrompt: '系统提示词（可选，用于定义工具调用等）',
      agentPersonaDefinition: '人格定义',
      saveAgent: '保存智能体',
      deleteAgent: '删除智能体',
      deleteAgentConfirm: '确定删除智能体"{name}"吗？',
      agentCreated: '智能体已创建',
      agentUpdated: '智能体已更新',
      agentDeleted: '智能体已删除',
      noAccess: '当前账号没有聊天管理权限',
      freeModel: '免费模型',
      reasoningModel: '推理模型',
      defaultModel: '设为默认模型',
      freeAgent: '免费智能体',
    },
  },
  'zh-TW': {
    common: {
      siteName: 'XiaoNiu Tech',
      blogName: 'XN Blog',
      chatName: 'XN Chat',
      loading: '載入中...',
      cancel: '取消',
      close: '關閉',
      confirm: '確認',
      save: '保存',
      saving: '保存中...',
      back: '返回',
      backHome: '返回主頁',
      previousPage: '上一頁',
      nextPage: '下一頁',
      clear: '清除',
      search: '搜尋',
      login: '登入',
      register: '註冊',
      loginOrRegister: '登入/註冊',
      logout: '登出',
      lightMode: '淺色',
      darkMode: '深色',
      guestMode: '訪客模式',
      upload: '上傳',
      retry: '重試',
      draft: '草稿',
      deleted: '已刪除',
      settings: '設定',
      edit: '編輯',
      delete: '刪除',
      restore: '恢復',
      permanentDelete: '永久刪除',
      manage: '管理',
      create: '建立',
      open: '開啟',
      email: '電子郵件',
      password: '密碼',
      nickname: '暱稱',
      bio: '簡介',
      language: '語言',
      theme: '主題',
      words: '字',
      articles: '篇文章',
      comments: '評論',
      likes: '讚',
      views: '閱讀',
      untitledChat: '新對話',
      assistantName: 'AI 助手',
      agentName: '智能體',
      agentConversation: '智能體對話',
    },
    time: {
      justNow: '剛剛',
      minutesAgo: '{count} 分鐘前',
      hoursAgo: '{count} 小時前',
      daysAgo: '{count} 天前',
    },
    home: {
      eyebrow: '個人軌道',
      heroTitle: 'XiaoNiu Tech',
      heroSubtitle: '把我的聊天實驗、技術文章和常用入口整理到同一個個人站點。',
      actionChat: 'Chat',
      actionBlog: '部落格',
      actionGithub: 'Github',
      featureChatTitle: 'Chat Lab',
      featureChatDesc: '多模型聊天、智能體會話與工作流實驗。',
      featureBlogTitle: '技術部落格',
      featureBlogDesc: '工程記錄、經驗總結與長期寫作。',
      featureGithubTitle: 'Github 倉庫',
      featureGithubDesc: '開源專案、腳本工具和程式實驗。',
      featureGamesTitle: '小遊戲',
      featureGamesDesc: '輕量互動原型與設計練習。',
      featureTagProduct: 'Product Surface',
      featureTagWriting: 'Writing',
      featureTagCode: 'Codebase',
      featureTagSandbox: 'Sandbox',
      open: 'Open',
      navTitle: 'XiaoNiu Tech',
      navLogin: '登入',
      navRegister: '註冊',
      navTheme: '切換主題',
      navLanguage: '切換語言',
      heroKicker: 'Digital Workspace',
      heroSummaryLead: '從 AI 對話到技術寫作，所有入口在同一張首頁中完成編排。',
      heroSummaryBody: '更輕的導覽、更少的雜訊，以及為長期迭代預留的清晰結構。',
      orbitCardHint: '點擊軌道產生彗星，懸浮時會出現粒子效果。',
      orbitSunTitle: '點擊太陽觸發超新星',
      statusTitle: '目前可用',
      statusOneLabel: 'Chat',
      statusOneValue: '多模型串流會話',
      statusTwoLabel: 'Blog',
      statusTwoValue: '寫作與發布',
      statusThreeLabel: 'Profile',
      statusThreeValue: '設定與頭像管理',
      footerBuiltBy: 'BUILT BY LITTLEFOGCAT',
      footerEmail: '郵件',
      footerGithub: 'GitHub',
      footerQQ: 'QQ',
      footerWechat: '微信',
      footerWechatQrAlt: '微信二維碼',
    },
    placeholder: {
      comingSoon: '即將開放',
      backHome: '返回首頁',
      enterChat: '進入 Chat',
      gamesTitle: '小遊戲',
      gamesDescription: '暫未開放，敬請期待。',
    },
    login: {
      pageTitle: '登入 - XN',
      title: 'XiaoNiu Tech',
      welcomeBack: '歡迎回來，請登入',
      registerIntro: '註冊新帳號並完成信箱驗證',
      loginTab: '登入',
      registerTab: '註冊',
      emailPlaceholder: '請輸入電子郵件',
      passwordPlaceholder: '請輸入密碼',
      newPasswordPlaceholder: '請設定密碼，至少 8 位',
      loginLoading: '登入中...',
      guestAccess: '訪客進入',
      captchaTitle: '人機驗證',
      captchaDescription: '請回答下面的算術題',
      captchaLoading: '驗證題載入中...',
      captchaRefresh: '刷新題目',
      captchaAnswerPlaceholder: '輸入答案',
      sendCode: '發送驗證碼',
      sendCodeLoading: '發送中...',
      codePlaceholder: '請輸入信箱驗證碼',
      verifyAndLogin: '驗證並登入',
      verifyLoading: '驗證中...',
      resendIn: '{seconds} 秒後可重新發送',
      switchToLogin: '返回登入',
      back: '返回',
      loadCaptchaFailed: '載入人機驗證失敗',
      loginFailed: '登入失敗，請重試',
      sendCodeFailed: '發送驗證碼失敗',
      verifyFailed: '驗證失敗，請重試',
      codeSentNotice: '驗證碼已發送至 {email}，10 分鐘內有效。',
      codeResendNotice: '{seconds} 秒後可重新發送。',
    },
    blog: {
      pageTitle: 'XN Blog',
      searchPlaceholder: '搜尋文章...',
      backHomeTitle: '返回主頁',
      managePosts: '管理文章',
      createMenu: '創作',
      createPost: '寫部落格',
      importPosts: '匯入文章',
      settings: '設定',
      logout: '登出',
      importTitle: '匯入文章',
      importHint: '僅支援匯入 .md 檔案。你可以一次選擇多個 Markdown 檔案，或直接選擇一個資料夾批次匯入。',
      selectFiles: '選擇檔案',
      selectFolder: '選擇資料夾',
      importing: '匯入中...',
      importNothing: '未能匯入任何文章',
      importSummarySuccess: '成功匯入 {count} 篇文章草稿。',
      importSummaryFailed: '失敗 {count} 篇。',
      importFirstError: '第一個錯誤：{message}',
      tagFilter: '標籤：',
      noPosts: '暫無文章',
      noMatchedPosts: '未找到匹配的文章',
      readCount: '{count} 閱讀',
      likeCount: '{count} 讚',
      commentCount: '{count} 評論',
      readCountLong: '{count} 次閱讀',
      likeCountLong: '{count} 次點讚',
      backToBlog: '返回部落格首頁',
      postNotFound: '文章不存在',
      postMissing: '該文章未找到或已被刪除',
      liked: '已讚',
      like: '點讚',
      editPost: '編輯文章',
      commentsTitle: '評論 ({count})',
      commentPlaceholder: '寫下你的評論...',
      submitComment: '發表評論',
      commentSubmitting: '提交中...',
      loginToComment: '登入後即可發表評論',
      noComments: '暫無評論',
      sidebarIntro: '全端開發者，專注於 Web 技術與 AI 應用。',
      totalWords: '總字數',
      tagCollection: '標籤合集',
      noTags: '暫無標籤',
      editorTitlePlaceholder: '文章標題...',
      editorTagsPlaceholder: '標籤，以逗號分隔...',
      editorContentPlaceholder: '使用 Markdown 撰寫內容...',
      editorPreview: '預覽',
      editorEmptyPreview: '*暫無內容*',
      saveDraft: '存草稿',
      publishing: '發布中...',
      publish: '發布',
      saveFailed: '保存失敗，請稍後再試。',
      unpublish: '撤回',
      writePageTitle: '寫部落格 - XN Blog',
      editPageTitle: '編輯: {title} - XN Blog',
      managePageTitle: '文章管理 - XN Blog',
      userNotFound: '用戶不存在',
      articlesTitle: '文章',
      articleCount: '{count} 篇文章',
      wordCount: '{count} 字',
      mixedStats: '{views} 閱讀 · {likes} 讚 · {comments} 評論',
      myPosts: '我的文章 ({count})',
      trashBin: '垃圾桶 ({count})',
      batchModeOn: '批量管理',
      batchModeOff: '完成批量管理',
      selectAllCurrent: '全選目前列表',
      selectedCount: '已選 {count} 篇',
      clearSelection: '清空選擇',
      bulkPublish: '批量發布',
      bulkUnpublish: '批量撤回',
      bulkDelete: '批量刪除',
      bulkRestore: '批量恢復',
      bulkPermanentDelete: '批量永久刪除',
      trashEmpty: '垃圾桶為空',
      deletedAt: '刪除於 {date}',
      bulkActionFailed: '批量操作失敗',
      trashConfirmOne: '確定要刪除這篇文章嗎？它將移入垃圾桶。',
      trashConfirmMany: '確定要將選中的 {count} 篇文章移入垃圾桶嗎？',
      permanentDeleteConfirmOne: '此操作不可撤銷，確定要永久刪除這篇文章及其所有評論嗎？',
      permanentDeleteConfirmMany: '此操作不可撤銷，確定要永久刪除選中的 {count} 篇文章及其評論嗎？',
      emptyDelete: '未選擇要刪除的文章。',
      emptyRestore: '未選擇要恢復的文章。',
      emptyPermanentDelete: '未選擇要永久刪除的文章。',
      emptyDraftPublish: '請至少選擇一篇草稿文章。',
      emptyPublishedUnpublish: '請至少選擇一篇已發布文章。',
      movedToTrash: '已將 {count} 篇文章移入垃圾桶。',
      restoredPosts: '已恢復 {count} 篇文章。',
      permanentlyDeleted: '已永久刪除 {count} 篇文章。',
      publishedPosts: '已發布 {count} 篇文章。',
      unpublishedPosts: '已將 {count} 篇文章撤回為草稿。',
      profileLoadingFailed: '載入用戶資訊失敗',
    },
    stock: {
      listPageTitle: '股市復盤 - XiaoNiu Tech',
      listDescription: '依日期回顧熱點板塊、消息面與次日關注方向。',
      heroEyebrow: 'Stock Review',
      heroTitle: '股市復盤',
      heroSubtitle: '把盤後觀察整理成結構化記錄，方便回查熱點、消息與明日關注線索。',
      statsTotal: '記錄數',
      statsCurrentPage: '目前頁',
      statsLatestDate: '最新日期',
      noPermission: '目前帳號沒有股市復盤查看權限',
      noCreatePermission: '目前帳號沒有建立股市復盤的權限',
      noUpdatePermission: '目前帳號沒有編輯股市復盤的權限',
      loadProfileFailed: '載入用戶資訊失敗',
      loadListFailed: '載入復盤列表失敗',
      loadDetailFailed: '載入復盤詳情失敗',
      filtersTitle: '篩選條件',
      filtersDescription: '依關鍵字、日期與板塊快速定位復盤記錄。',
      searchPlaceholder: '搜尋標題、板塊、個股或理由',
      sectorPlaceholder: '板塊關鍵字',
      allImpactLevels: '全部影響等級',
      impactPositive: '利多',
      impactNegative: '利空',
      impactNeutral: '中性',
      applyFilters: '套用篩選',
      resetFilters: '重置',
      createReview: '新建復盤',
      listTitle: '復盤列表',
      listDescriptionShort: '依日期倒序顯示摘要，點擊進入完整詳情。',
      loadingList: '正在載入復盤列表...',
      noReviews: '目前篩選條件下沒有復盤記錄',
      articleTitle: '{date} 復盤',
      newsCount: '{count} 則消息',
      summaryFromFocus: '關注方向',
      summaryFromHot: '熱點概覽',
      emptySummary: '暫無摘要，點擊查看完整內容。',
      timeUnknown: '未標註時間',
      detailPageTitle: '{date} 股市復盤 - XiaoNiu Tech',
      detailDescription: '查看單日股市復盤的完整詳情。',
      detailTitle: '復盤詳情',
      editorCreateTitle: '新建股市復盤 - XiaoNiu Tech',
      editorEditTitle: '編輯股市復盤 - XiaoNiu Tech',
      editorDescription: '維護當日熱點、消息面、關注板塊與明日關注個股。',
      createMode: '新建復盤',
      editMode: '編輯復盤',
      articleLead: '圍繞當日行情脈絡整理盤後結論，作為次日回查與盤前準備的統一入口。',
      backToList: '返回列表',
      emptyDetail: '找不到對應的復盤記錄。',
      created: '復盤已建立',
      updated: '復盤已更新',
      saveFailed: '保存復盤失敗',
      deleteConfirm: '確定要刪除目前復盤記錄嗎？此操作不可撤銷。',
      deleteFailed: '刪除復盤失敗',
      editorDateEyebrow: 'Header',
      editorDateTitle: '復盤日期',
      editorDateDescription: '預設帶入當天日期；如有需要，可建立同一天的多條復盤記錄。',
      marketsEyebrow: 'Market Overview',
      marketsTitle: '市場總覽',
      marketsDescription: '維護市場摘要、指數表現與量能描述。',
      fieldMarketSummary: '市場摘要',
      fieldMarketVolume: '量能描述',
      indicesTitle: '指數列表',
      sectionIndexItem: '指數 {index}',
      fieldIndexCode: '指數代碼',
      fieldIndexName: '指數名稱',
      fieldClosePrice: '收盤價',
      topSectorsEyebrow: 'Top Sectors',
      topSectorsTitle: '今日熱點',
      topSectorsDescription: '記錄產業板塊、概念板塊、領跌板塊與熱點總結。',
      conceptsTitle: '熱點概念',
      fallingSectorsTitle: '領跌板塊',
      todayHotSummaryLabel: '熱點總結',
      sectionHotItem: '熱點 {index}',
      removeItem: '刪除',
      addItem: '新增一項',
      fieldSectorName: '板塊名稱',
      fieldChangePercent: '漲幅，例如 3.5',
      fieldTopStocks: '每行一條：代碼 | 名稱 | 漲跌幅',
      newsEyebrow: 'Market News',
      newsTitle: '消息面',
      newsDescription: '按分類整理消息面，每行輸入一條 markdown 內容。',
      sectionNewsItem: '消息 {index}',
      fieldNewsTitle: '標題',
      fieldNewsSummary: '摘要',
      fieldNewsDetail: '每行一條 markdown 內容',
      fieldNewsSource: '來源，可選',
      fieldPublishTime: 'YYYY-MM-DD HH:mm:ss',
      fieldImpactSectors: '受影響板塊，使用逗號分隔',
      focusSectorsEyebrow: 'Sectors To Watch',
      focusSectorsTitle: '關注板塊',
      focusSectorsDescription: '記錄次日重點觀察或持續持有的方向。',
      sectionFocusSectorItem: '關注板塊 {index}',
      fieldReason: '關注理由',
      focusStocksEyebrow: 'Stocks To Watch',
      focusStocksTitle: '明日關注個股',
      focusStocksDescription: '按板塊整理次日關注個股，每行一條：代碼 | 名稱 | 理由。',
      sectionFocusStockItem: '個股分組 {index}',
      fieldFocusStocksLines: '每行一條：代碼 | 名稱 | 理由',
      fieldStockCode: '股票代碼',
      fieldStockName: '股票名稱',
      noTopSectors: '暫無熱點板塊記錄',
      topStocksLabel: '領漲股代碼',
      noNews: '暫無消息面記錄',
      sourceUnknown: '來源未標註',
      noFocusSectors: '暫無關注板塊',
      noFocusStocks: '暫無關注個股',
    },
    settings: {
      pageTitle: '使用者設定 - XN Blog',
      profileLoadingFailed: '載入使用者資訊失敗',
      avatarUpdated: '頭像已更新',
      avatarSaveFailed: '頭像保存失敗：{message}',
      currentPasswordRequired: '修改密碼需要輸入目前密碼',
      saveSuccess: '保存成功',
      saveSuccessHint: '個人資料已更新。關閉提示後將返回上一頁。',
      avatar: '頭像',
      emailReadonly: '電子郵件不可更改',
      nicknamePlaceholder: '設定暱稱',
      bioPlaceholder: '寫一段個人簡介...',
      currentPasswordPlaceholder: '如需修改密碼，請輸入目前密碼',
      newPasswordPlaceholder: '輸入新密碼（至少 8 位字元）',
      saving: '保存中...',
      cancel: '取消',
      backPrevious: '返回前頁',
      title: '使用者設定',
    },
    avatar: {
      chooseFile: '請選擇檔案',
      unsupportedType: '不支援的檔案類型，僅允許 JPEG、PNG、GIF、WebP',
      unsupportedFormat: '不支援的圖片格式',
      fileTooLarge: '檔案過大（{size}MB），上限為 5MB',
      imageProcessFailed: '圖片處理失敗',
      imageLoadFailed: '圖片載入失敗',
      uploadFailed: '上傳失敗',
      avatarAlt: '頭像',
      uploadAvatar: '上傳頭像',
      changeAvatar: '更換頭像',
      clickToUpload: '點擊上傳頭像',
      clickToEdit: '點擊修改頭像',
      modalTitle: '修改頭像',
      previewAlt: '預覽',
      currentAvatarAlt: '目前頭像',
      reselect: '重新選擇',
      selectImage: '選擇圖片',
      supportHint: '支援 JPEG / PNG / GIF / WebP，最大 5MB，長邊自動縮放至 1024px',
      uploading: '上傳中...',
      confirm: '確認',
    },
    chat: {
      pageTitle: 'XN Chat',
      selectIdentityTitle: '選擇智能體 | XN Chat',
      currentSession: '目前會話：{name}',
      currentCompact: '目前：{name}',
      workspaceTitle: '聊天記錄',
      workspaceLabel: 'Workspace',
      newChat: '新建聊天',
      openHistory: '打開聊天記錄',
      closeHistory: '關閉聊天記錄',
      emptyChats: '還沒有會話，先開始一段新的對話。',
      deleteChat: '刪除會話',
      expandSidebar: '展開側邊欄',
      collapseSidebar: '收起側邊欄',
      multiModelWorkbench: '多模型對話工作台',
      streamWorkbench: '多模型串流聊天工作台',
      addAgent: '添加智能體',
      openActions: '打開操作選單',
      actionsLabel: 'Actions',
      actionsTitle: '聊天操作',
      backBottom: '回到底部',
      loadFailed: '載入失敗',
      loadingModels: '載入中...',
      linkedAgent: 'Agent Linked',
      startConversationWith: '和 {name} 開始一段新對話',
      linkedAgentDescription: '這個智能體已經綁定到當前會話，發送第一條消息後，對話會自動切換到底部輸入模式。',
      neuralConsole: 'Neural Console',
      heroTitle: '在這裡開始下一段高效對話',
      heroDesc: '支援多模型、串流回覆和智能體人設。',
      badgeStreaming: '串流回覆',
      badgeMobile: '行動端適配',
      badgeIdentity: '智能體綁定',
      guestLimitCreate: '訪客聊天記錄已達到 {limit} 條上限，請登入後繼續建立新會話。',
      guestLimitContinue: '訪客聊天記錄已達到 {limit} 條上限，請登入後繼續。',
      modelPlaceholder: '選擇模型',
      authLoginTitle: '返回登入頁',
      authLogoutTitle: '登出',
      identityLab: 'Identity Lab',
      chooseAgentStart: '選擇一個智能體開始對話',
      identityLabDesc: '智能體由服務端讀取人格設定檔生成。每個智能體最多綁定一個會話，已存在的會話不會重複建立。',
      backToChat: '返回聊天',
      noIdentityAvailable: '暫無可用智能體，請在服務端配置 identities 目錄後重試。',
      agentIndex: 'Agent {index}',
      identityUsed: '已存在會話',
      noDescription: '暫無描述',
      identityBinding: '綁定形式：單智能體單會話',
      enterConversation: '進入對話',
      createConversation: '建立對話',
      assistantRole: 'Assistant',
      meRole: 'Me',
      thinking: '正在思考',
      reasoningSummary: '已思考（用時 {seconds} 秒）',
      showReasoning: '顯示思考過程',
      hideReasoning: '隱藏思考過程',
      copy: '複製',
      copied: '已複製',
      regenerate: '重新生成',
      messagePlaceholder: '發送消息...',
      importantNotice: 'AI 可能會產生錯誤資訊，請核實重要內容',
      errorPrefix: '錯誤: {message}',
      assistantAvatarAlt: '{name} 頭像',
      assistantFallbackAvatarAlt: '{name} 預設頭像',
    },
    chatManage: {
      pageTitle: '聊天管理',
      chatModule: 'Chat Module',
      modelConfig: '模型配置',
      agentConfig: '智能體配置',
      newModel: '新建模型',
      newAgent: '新建智能體',
      modelProvider: '提供商',
      modelId: '模型 ID',
      modelDisplayName: '顯示名稱',
      modelInputType: '輸入類型（逗號分隔）',
      modelContextWindow: '上下文視窗',
      modelMaxTokens: '最大輸出 Token',
      providerConfig: '提供商請求配置（providerConfig）',
      compatConfig: '相容擴展參數（compat）',
      saveModel: '保存模型',
      deleteModel: '刪除模型',
      deleteModelConfirm: '確定刪除模型"{name}"嗎？',
      copyModel: '複製模型',
      modelCopied: '模型已複製',
      modelCreated: '模型配置已建立',
      modelUpdated: '模型配置已更新',
      modelDeleted: '模型配置已刪除',
      agentId: '智能體 ID（建立後不可修改）',
      agentName: '名稱',
      agentRole: '角色標籤',
      agentAvatar: '頭像',
      agentAvatarUrl: '頭像 URL',
      agentDescription: '簡介',
      agentSystemPrompt: '系統提示詞（可選，用於定義工具調用等）',
      agentPersonaDefinition: '人格定義',
      saveAgent: '保存智能體',
      deleteAgent: '刪除智能體',
      deleteAgentConfirm: '確定刪除智能體"{name}"嗎？',
      agentCreated: '智能體已建立',
      agentUpdated: '智能體已更新',
      agentDeleted: '智能體已刪除',
      noAccess: '目前帳號沒有聊天管理權限',
      freeModel: '免費模型',
      reasoningModel: '推理模型',
      defaultModel: '設為預設模型',
      freeAgent: '免費智能體',
    },
  },
  'en-US': {
    common: {
      siteName: 'XiaoNiu Tech',
      blogName: 'XN Blog',
      chatName: 'XN Chat',
      loading: 'Loading...',
      cancel: 'Cancel',
      close: 'Close',
      confirm: 'Confirm',
      save: 'Save',
      saving: 'Saving...',
      back: 'Back',
      backHome: 'Back Home',
      previousPage: 'Previous',
      nextPage: 'Next',
      clear: 'Clear',
      search: 'Search',
      login: 'Log In',
      register: 'Register',
      loginOrRegister: 'Log In / Register',
      logout: 'Log Out',
      lightMode: 'Light',
      darkMode: 'Dark',
      guestMode: 'Guest Mode',
      upload: 'Upload',
      retry: 'Retry',
      draft: 'Draft',
      deleted: 'Deleted',
      settings: 'Settings',
      edit: 'Edit',
      delete: 'Delete',
      restore: 'Restore',
      permanentDelete: 'Delete Permanently',
      manage: 'Manage',
      create: 'Create',
      open: 'Open',
      email: 'Email',
      password: 'Password',
      nickname: 'Nickname',
      bio: 'Bio',
      language: 'Language',
      theme: 'Theme',
      words: 'words',
      articles: 'articles',
      comments: 'comments',
      likes: 'likes',
      views: 'views',
      untitledChat: 'New Chat',
      assistantName: 'AI Assistant',
      agentName: 'Agent',
      agentConversation: 'Agent Conversation',
    },
    time: {
      justNow: 'Just now',
      minutesAgo: '{count} min ago',
      hoursAgo: '{count} hr ago',
      daysAgo: '{count} day ago',
    },
    home: {
      eyebrow: 'Personal Orbit',
      heroTitle: 'XiaoNiu Tech',
      heroSubtitle: 'A personal site for my chat experiments, technical writing, and everyday tools.',
      actionChat: 'Chat',
      actionBlog: 'Blog',
      actionGithub: 'Github',
      featureChatTitle: 'Chat Lab',
      featureChatDesc: 'Multi-model chat, agent sessions, and workflow experiments.',
      featureBlogTitle: 'Tech Blog',
      featureBlogDesc: 'Engineering notes, reflections, and long-form writing.',
      featureGithubTitle: 'Github Repo',
      featureGithubDesc: 'Open-source work, automation scripts, and code experiments.',
      featureGamesTitle: 'Mini Games',
      featureGamesDesc: 'Interactive prototypes and playful UI studies.',
      featureTagProduct: 'Product Surface',
      featureTagWriting: 'Writing',
      featureTagCode: 'Codebase',
      featureTagSandbox: 'Sandbox',
      open: 'Open',
      navTitle: 'XiaoNiu Tech',
      navLogin: 'Log In',
      navRegister: 'Register',
      navTheme: 'Toggle theme',
      navLanguage: 'Switch language',
      heroKicker: 'Digital Workspace',
      heroSummaryLead: 'One landing page that orchestrates AI chat, writing, and personal tooling.',
      heroSummaryBody: 'Less noise, clearer navigation, and a structure that can keep evolving over time.',
      orbitCardHint: 'Click the orbit to launch a comet. Hovering reveals particle fireworks.',
      orbitSunTitle: 'Click the sun to trigger a supernova',
      statusTitle: 'Live Now',
      statusOneLabel: 'Chat',
      statusOneValue: 'Multi-model streaming sessions',
      statusTwoLabel: 'Blog',
      statusTwoValue: 'Writing and publishing',
      statusThreeLabel: 'Profile',
      statusThreeValue: 'Settings and avatar management',
      footerBuiltBy: 'BUILT BY LITTLEFOGCAT',
      footerEmail: 'Email',
      footerGithub: 'GitHub',
      footerQQ: 'QQ',
      footerWechat: 'WeChat',
      footerWechatQrAlt: 'WeChat QR code',
    },
    placeholder: {
      comingSoon: 'Coming Soon',
      backHome: 'Back Home',
      enterChat: 'Open Chat',
      gamesTitle: 'Mini Games',
      gamesDescription: 'This section is not available yet.',
    },
    login: {
      pageTitle: 'Log In - XN',
      title: 'XiaoNiu Tech',
      welcomeBack: 'Welcome back. Sign in to continue.',
      registerIntro: 'Create a new account and finish email verification.',
      loginTab: 'Log In',
      registerTab: 'Register',
      emailPlaceholder: 'Enter your email',
      passwordPlaceholder: 'Enter your password',
      newPasswordPlaceholder: 'Set a password with at least 8 characters',
      loginLoading: 'Signing in...',
      guestAccess: 'Continue as Guest',
      captchaTitle: 'Human Check',
      captchaDescription: 'Answer the arithmetic question below.',
      captchaLoading: 'Loading captcha...',
      captchaRefresh: 'Refresh',
      captchaAnswerPlaceholder: 'Your answer',
      sendCode: 'Send Code',
      sendCodeLoading: 'Sending...',
      codePlaceholder: 'Enter the verification code',
      verifyAndLogin: 'Verify and Sign In',
      verifyLoading: 'Verifying...',
      resendIn: 'Resend in {seconds}s',
      switchToLogin: 'Back to login',
      back: 'Back',
      loadCaptchaFailed: 'Failed to load captcha',
      loginFailed: 'Sign in failed. Please try again.',
      sendCodeFailed: 'Failed to send verification code',
      verifyFailed: 'Verification failed. Please try again.',
      codeSentNotice: 'A verification code has been sent to {email}. It expires in 10 minutes.',
      codeResendNotice: ' Resend available in {seconds}s.',
    },
    blog: {
      pageTitle: 'XN Blog',
      searchPlaceholder: 'Search posts...',
      backHomeTitle: 'Back Home',
      managePosts: 'Manage Posts',
      createMenu: 'Create',
      createPost: 'Write Post',
      importPosts: 'Import Posts',
      settings: 'Settings',
      logout: 'Log Out',
      importTitle: 'Import Articles',
      importHint: 'Only .md files are supported. You can pick multiple Markdown files at once or select an entire folder for batch import.',
      selectFiles: 'Choose Files',
      selectFolder: 'Choose Folder',
      importing: 'Importing...',
      importNothing: 'No article was imported',
      importSummarySuccess: '{count} draft article(s) imported successfully.',
      importSummaryFailed: '{count} item(s) failed.',
      importFirstError: 'First error: {message}',
      tagFilter: 'Tag:',
      noPosts: 'No posts yet',
      noMatchedPosts: 'No posts matched your search',
      readCount: '{count} reads',
      likeCount: '{count} likes',
      commentCount: '{count} comments',
      readCountLong: '{count} reads',
      likeCountLong: '{count} likes',
      backToBlog: 'Back to Blog',
      postNotFound: 'Post Not Found',
      postMissing: 'This post could not be found or has been removed.',
      liked: 'Liked',
      like: 'Like',
      editPost: 'Edit Post',
      commentsTitle: 'Comments ({count})',
      commentPlaceholder: 'Write a comment...',
      submitComment: 'Post Comment',
      commentSubmitting: 'Submitting...',
      loginToComment: 'Log in to comment',
      noComments: 'No comments yet',
      sidebarIntro: 'Full-stack developer focused on web engineering and AI-enabled products.',
      totalWords: 'Words',
      tagCollection: 'Tags',
      noTags: 'No tags yet',
      editorTitlePlaceholder: 'Post title...',
      editorTagsPlaceholder: 'Tags, separated by commas...',
      editorContentPlaceholder: 'Write in Markdown...',
      editorPreview: 'Preview',
      editorEmptyPreview: '*Nothing here yet*',
      saveDraft: 'Save Draft',
      publishing: 'Publishing...',
      publish: 'Publish',
      saveFailed: 'Failed to save the post. Please try again later.',
      unpublish: 'Unpublish',
      writePageTitle: 'Write - XN Blog',
      editPageTitle: 'Edit: {title} - XN Blog',
      managePageTitle: 'Manage Posts - XN Blog',
      userNotFound: 'User Not Found',
      articlesTitle: 'Posts',
      articleCount: '{count} posts',
      wordCount: '{count} words',
      mixedStats: '{views} reads · {likes} likes · {comments} comments',
      myPosts: 'My Posts ({count})',
      trashBin: 'Trash ({count})',
      batchModeOn: 'Batch Manage',
      batchModeOff: 'Done',
      selectAllCurrent: 'Select current list',
      selectedCount: '{count} selected',
      clearSelection: 'Clear selection',
      bulkPublish: 'Publish Selected',
      bulkUnpublish: 'Unpublish Selected',
      bulkDelete: 'Move to Trash',
      bulkRestore: 'Restore Selected',
      bulkPermanentDelete: 'Delete Permanently',
      trashEmpty: 'Trash is empty',
      deletedAt: 'Deleted at {date}',
      bulkActionFailed: 'Batch action failed',
      trashConfirmOne: 'Move this post to trash?',
      trashConfirmMany: 'Move {count} selected post(s) to trash?',
      permanentDeleteConfirmOne: 'This cannot be undone. Permanently delete this post and all comments?',
      permanentDeleteConfirmMany: 'This cannot be undone. Permanently delete {count} selected post(s) and related comments?',
      emptyDelete: 'No post selected for deletion.',
      emptyRestore: 'No trashed post selected.',
      emptyPermanentDelete: 'No post selected for permanent deletion.',
      emptyDraftPublish: 'Select at least one draft post.',
      emptyPublishedUnpublish: 'Select at least one published post.',
      movedToTrash: '{count} post(s) moved to trash.',
      restoredPosts: '{count} post(s) restored.',
      permanentlyDeleted: '{count} post(s) permanently deleted.',
      publishedPosts: '{count} post(s) published.',
      unpublishedPosts: '{count} post(s) reverted to draft.',
      profileLoadingFailed: 'Failed to load user profile',
    },
    stock: {
      listPageTitle: 'Stock Review - XiaoNiu Tech',
      listDescription: 'Review sector leaders, market news, and next-session watchlists by date.',
      heroEyebrow: 'Stock Review',
      heroTitle: 'Stock Review',
      heroSubtitle: 'Turn end-of-day observations into structured notes for quick review before the next session.',
      statsTotal: 'Records',
      statsCurrentPage: 'Page',
      statsLatestDate: 'Latest Date',
      noPermission: 'This account does not have permission to view stock reviews.',
      noCreatePermission: 'This account does not have permission to create stock reviews.',
      noUpdatePermission: 'This account does not have permission to edit stock reviews.',
      loadProfileFailed: 'Failed to load user profile',
      loadListFailed: 'Failed to load stock review list',
      loadDetailFailed: 'Failed to load stock review details',
      filtersTitle: 'Filters',
      filtersDescription: 'Find records quickly by keywords, dates, and sectors.',
      searchPlaceholder: 'Search titles, sectors, stocks, or reasons',
      sectorPlaceholder: 'Sector keyword',
      allImpactLevels: 'All impact levels',
      impactPositive: 'Positive',
      impactNegative: 'Negative',
      impactNeutral: 'Neutral',
      applyFilters: 'Apply Filters',
      resetFilters: 'Reset',
      createReview: 'New Review',
      listTitle: 'Review List',
      listDescriptionShort: 'Summaries are shown in reverse chronological order. Open one for full details.',
      loadingList: 'Loading stock review list...',
      noReviews: 'No stock reviews match the current filters.',
      articleTitle: '{date} Review',
      newsCount: '{count} news item(s)',
      summaryFromFocus: 'Watchlist',
      summaryFromHot: 'Market Snapshot',
      emptySummary: 'No summary yet. Open the record to read the full details.',
      timeUnknown: 'Time not specified',
      detailPageTitle: '{date} Stock Review - XiaoNiu Tech',
      detailDescription: 'Read the full details of a single stock review.',
      detailTitle: 'Review Details',
      editorCreateTitle: 'Create Stock Review - XiaoNiu Tech',
      editorEditTitle: 'Edit Stock Review - XiaoNiu Tech',
      editorDescription: 'Maintain sector leaders, market news, watch sectors, and watch stocks for the next session.',
      createMode: 'Create Review',
      editMode: 'Edit Review',
      articleLead: 'Capture the market narrative of the day in one place for next-day review and preparation.',
      backToList: 'Back to List',
      emptyDetail: 'The requested stock review was not found.',
      created: 'Stock review created.',
      updated: 'Stock review updated.',
      saveFailed: 'Failed to save stock review',
      deleteConfirm: 'Delete this stock review? This action cannot be undone.',
      deleteFailed: 'Failed to delete stock review',
      editorDateEyebrow: 'Header',
      editorDateTitle: 'Review Date',
      editorDateDescription: 'The current date is filled in by default, and multiple reviews can share the same date when needed.',
      marketsEyebrow: 'Market Overview',
      marketsTitle: 'Market Overview',
      marketsDescription: 'Maintain the daily market summary, index moves, and volume notes.',
      fieldMarketSummary: 'Market summary',
      fieldMarketVolume: 'Volume note',
      indicesTitle: 'Indices',
      sectionIndexItem: 'Index {index}',
      fieldIndexCode: 'Index code',
      fieldIndexName: 'Index name',
      fieldClosePrice: 'Close price',
      topSectorsEyebrow: 'Top Sectors',
      topSectorsTitle: 'Top Sectors',
      topSectorsDescription: 'Maintain sector leaders, concept themes, laggards, and a daily hot-summary.',
      conceptsTitle: 'Concept Themes',
      fallingSectorsTitle: 'Falling Sectors',
      todayHotSummaryLabel: 'Hot summary',
      sectionHotItem: 'Sector {index}',
      removeItem: 'Remove',
      addItem: 'Add Item',
      fieldSectorName: 'Sector name',
      fieldChangePercent: 'Change %, for example 3.5',
      fieldTopStocks: 'One line per stock: code | name | change %',
      newsEyebrow: 'Market News',
      newsTitle: 'Market News',
      newsDescription: 'Group market news by topic, one markdown line per item.',
      sectionNewsItem: 'News {index}',
      fieldNewsTitle: 'Title',
      fieldNewsSummary: 'Summary',
      fieldNewsDetail: 'One markdown item per line',
      fieldNewsSource: 'Source, optional',
      fieldPublishTime: 'YYYY-MM-DD HH:mm:ss',
      fieldImpactSectors: 'Impacted sectors, separated by commas',
      focusSectorsEyebrow: 'Sectors To Watch',
      focusSectorsTitle: 'Sectors To Watch',
      focusSectorsDescription: 'Record sectors to monitor or continue holding next session.',
      sectionFocusSectorItem: 'Watch sector {index}',
      fieldReason: 'Reason',
      focusStocksEyebrow: 'Stocks To Watch',
      focusStocksTitle: 'Stocks To Watch',
      focusStocksDescription: 'Organize next-session watch stocks by sector, one line per stock: code | name | reason.',
      sectionFocusStockItem: 'Stock group {index}',
      fieldFocusStocksLines: 'One line per stock: code | name | reason',
      fieldStockCode: 'Ticker',
      fieldStockName: 'Stock name',
      noTopSectors: 'No top sector records yet.',
      topStocksLabel: 'Leading tickers',
      noNews: 'No market news records yet.',
      sourceUnknown: 'Source not specified',
      noFocusSectors: 'No watch sectors yet.',
      noFocusStocks: 'No watch stocks yet.',
    },
    settings: {
      pageTitle: 'Settings - XN Blog',
      profileLoadingFailed: 'Failed to load user profile',
      avatarUpdated: 'Avatar updated',
      avatarSaveFailed: 'Failed to save avatar: {message}',
      currentPasswordRequired: 'Current password is required to change your password',
      saveSuccess: 'Saved successfully',
      saveSuccessHint: 'Your profile was updated. Closing this dialog will return to the previous page.',
      avatar: 'Avatar',
      emailReadonly: 'Email cannot be changed',
      nicknamePlaceholder: 'Set a nickname',
      bioPlaceholder: 'Write a short bio...',
      currentPasswordPlaceholder: 'Enter your current password to change it',
      newPasswordPlaceholder: 'Enter a new password (minimum 8 characters)',
      saving: 'Saving...',
      cancel: 'Cancel',
      backPrevious: 'Back',
      title: 'User Settings',
    },
    avatar: {
      chooseFile: 'Please choose a file',
      unsupportedType: 'Unsupported file type. Only JPEG, PNG, GIF, and WebP are allowed.',
      unsupportedFormat: 'Unsupported image format',
      fileTooLarge: 'File too large ({size}MB). Maximum size is 5MB.',
      imageProcessFailed: 'Failed to process image',
      imageLoadFailed: 'Failed to load image',
      uploadFailed: 'Upload failed',
      avatarAlt: 'Avatar',
      uploadAvatar: 'Upload Avatar',
      changeAvatar: 'Change Avatar',
      clickToUpload: 'Click to upload avatar',
      clickToEdit: 'Click to change avatar',
      modalTitle: 'Update Avatar',
      previewAlt: 'Preview',
      currentAvatarAlt: 'Current avatar',
      reselect: 'Choose Again',
      selectImage: 'Select Image',
      supportHint: 'JPEG / PNG / GIF / WebP, up to 5MB, resized automatically to a 1024px long edge',
      uploading: 'Uploading...',
      confirm: 'Confirm',
    },
    chat: {
      pageTitle: 'XN Chat',
      selectIdentityTitle: 'Choose an Agent | XN Chat',
      currentSession: 'Current session: {name}',
      currentCompact: 'Current: {name}',
      workspaceTitle: 'Chat History',
      workspaceLabel: 'Workspace',
      newChat: 'New Chat',
      openHistory: 'Open chat history',
      closeHistory: 'Close chat history',
      emptyChats: 'No conversation yet. Start a new one.',
      deleteChat: 'Delete chat',
      expandSidebar: 'Expand sidebar',
      collapseSidebar: 'Collapse sidebar',
      multiModelWorkbench: 'Multi-model chat workspace',
      streamWorkbench: 'Streaming multi-model chat workspace',
      addAgent: 'Add Agent',
      openActions: 'Open action menu',
      actionsLabel: 'Actions',
      actionsTitle: 'Chat Actions',
      backBottom: 'Back to bottom',
      loadFailed: 'Load Failed',
      loadingModels: 'Loading...',
      linkedAgent: 'Agent Linked',
      startConversationWith: 'Start a new conversation with {name}',
      linkedAgentDescription: 'This agent is already bound to the current session. After your first message, the composer will move to the bottom automatically.',
      neuralConsole: 'Neural Console',
      heroTitle: 'Start the next focused conversation here',
      heroDesc: 'Multi-model chat with streaming responses and agent personas.',
      badgeStreaming: 'Streaming',
      badgeMobile: 'Mobile Ready',
      badgeIdentity: 'Agent Binding',
      guestLimitCreate: 'Guest chat history has reached the {limit}-session limit. Please log in to create another chat.',
      guestLimitContinue: 'Guest chat history has reached the {limit}-session limit. Please log in to continue.',
      modelPlaceholder: 'Choose model',
      authLoginTitle: 'Go to login',
      authLogoutTitle: 'Log out',
      identityLab: 'Identity Lab',
      chooseAgentStart: 'Choose an agent to begin',
      identityLabDesc: 'Agents are generated from persona definitions loaded by the server. Each agent can bind to at most one conversation, and existing sessions are reused.',
      backToChat: 'Back to Chat',
      noIdentityAvailable: 'No agents are available. Configure identities on the server and try again.',
      agentIndex: 'Agent {index}',
      identityUsed: 'Session exists',
      noDescription: 'No description yet',
      identityBinding: 'Binding: one agent, one conversation',
      enterConversation: 'Open Chat',
      createConversation: 'Create Chat',
      assistantRole: 'Assistant',
      meRole: 'Me',
      thinking: 'Thinking',
      reasoningSummary: 'Thought for {seconds}s',
      showReasoning: 'Show reasoning',
      hideReasoning: 'Hide reasoning',
      copy: 'Copy',
      copied: 'Copied',
      regenerate: 'Regenerate',
      messagePlaceholder: 'Send a message...',
      importantNotice: 'AI can be wrong. Please verify important information.',
      errorPrefix: 'Error: {message}',
      assistantAvatarAlt: '{name} avatar',
      assistantFallbackAvatarAlt: '{name} default avatar',
    },
    chatManage: {
      pageTitle: 'Chat Management',
      chatModule: 'Chat Module',
      modelConfig: 'Model Config',
      agentConfig: 'Agent Config',
      newModel: 'New Model',
      newAgent: 'New Agent',
      modelProvider: 'Provider',
      modelId: 'Model ID',
      modelDisplayName: 'Display Name',
      modelInputType: 'Input Types (comma separated)',
      modelContextWindow: 'Context Window',
      modelMaxTokens: 'Max Output Tokens',
      providerConfig: 'Provider Config (providerConfig)',
      compatConfig: 'Compatibility Options (compat)',
      saveModel: 'Save Model',
      deleteModel: 'Delete Model',
      deleteModelConfirm: 'Delete model "{name}"?',
      copyModel: 'Copy Model',
      modelCopied: 'Model copied',
      modelCreated: 'Model config created',
      modelUpdated: 'Model config updated',
      modelDeleted: 'Model config deleted',
      agentId: 'Agent ID (immutable after creation)',
      agentName: 'Name',
      agentRole: 'Role Tag',
      agentAvatar: 'Avatar',
      agentAvatarUrl: 'Avatar URL',
      agentDescription: 'Description',
      agentSystemPrompt: 'System Prompt (optional, for tool definitions etc.)',
      agentPersonaDefinition: 'Persona Definition',
      saveAgent: 'Save Agent',
      deleteAgent: 'Delete Agent',
      deleteAgentConfirm: 'Delete agent "{name}"?',
      agentCreated: 'Agent created',
      agentUpdated: 'Agent updated',
      agentDeleted: 'Agent deleted',
      noAccess: 'No chat management permission',
      freeModel: 'Free Model',
      reasoningModel: 'Reasoning Model',
      defaultModel: 'Set as Default Model',
      freeAgent: 'Free Agent',
    },
  },
};

const AppShellContext = createContext(null);

function resolveDictionary(locale) {
  return DICTIONARIES[locale] || DICTIONARIES[DEFAULT_LOCALE];
}

function getNestedMessage(dictionary, key) {
  return key.split('.').reduce((value, segment) => value?.[segment], dictionary);
}

function interpolate(template, params) {
  if (typeof template !== 'string' || !params) {
    return template;
  }

  return template.replace(/\{(\w+)\}/g, (_, token) => {
    const value = params[token];
    return value === undefined || value === null ? '' : String(value);
  });
}

function getStoredLocale() {
  if (typeof window === 'undefined') {
    return DEFAULT_LOCALE;
  }

  const stored = window.localStorage.getItem(APP_LOCALE_KEY);
  return LOCALE_OPTIONS.some(option => option.code === stored) ? stored : DEFAULT_LOCALE;
}

function getStoredTheme() {
  if (typeof window === 'undefined') {
    return DEFAULT_THEME;
  }

  const stored = window.localStorage.getItem(APP_THEME_KEY);
  return stored === 'light' || stored === 'dark' ? stored : DEFAULT_THEME;
}

export function AppShellProvider({ children }) {
  const [locale, setLocale] = useState(getStoredLocale);
  const [theme, setTheme] = useState(getStoredTheme);
  const hasThemeMountedRef = useRef(false);
  const themeTransitionTimerRef = useRef(null);
  const themeTransitionEventHandlerRef = useRef(null);
  const themeTransitionTokenRef = useRef(0);

  function clearThemeTransitionListeners() {
    const handler = themeTransitionEventHandlerRef.current;
    if (!handler) {
      return;
    }

    document.removeEventListener('transitioncancel', handler, true);
    document.removeEventListener('transitionend', handler, true);
    themeTransitionEventHandlerRef.current = null;
  }

  const dictionary = useMemo(() => resolveDictionary(locale), [locale]);

  const t = useCallback((key, params) => {
    const resolved = getNestedMessage(dictionary, key) ?? getNestedMessage(DICTIONARIES[DEFAULT_LOCALE], key) ?? key;
    return typeof resolved === 'string' ? interpolate(resolved, params) : resolved;
  }, [dictionary]);

  const formatDate = useCallback((valueToFormat, options) => {
    if (!valueToFormat) {
      return '';
    }

    const date = valueToFormat instanceof Date ? valueToFormat : new Date(valueToFormat);
    if (Number.isNaN(date.getTime())) {
      return '';
    }

    return new Intl.DateTimeFormat(locale, options).format(date);
  }, [locale]);

  const formatNumber = useCallback((valueToFormat) => new Intl.NumberFormat(locale).format(Number(valueToFormat) || 0), [locale]);

  const formatRelativeTime = useCallback((timestamp) => {
    const date = new Date(timestamp);
    if (Number.isNaN(date.getTime())) {
      return '';
    }

    const diff = Date.now() - date.getTime();
    if (diff < 60000) {
      return t('time.justNow');
    }
    if (diff < 3600000) {
      return t('time.minutesAgo', { count: Math.floor(diff / 60000) });
    }
    if (diff < 86400000) {
      return t('time.hoursAgo', { count: Math.floor(diff / 3600000) });
    }
    if (diff < 604800000) {
      return t('time.daysAgo', { count: Math.floor(diff / 86400000) });
    }

    return formatDate(date, { month: 'short', day: 'numeric' });
  }, [formatDate, t]);

  useEffect(() => {
    window.localStorage.setItem(APP_LOCALE_KEY, locale);
    document.documentElement.lang = locale;
  }, [locale]);

  useEffect(() => {
    window.localStorage.setItem(APP_THEME_KEY, theme);
    const root = document.documentElement;
    const { body } = document;
    const clearThemeTransitionClasses = () => {
      root.classList.remove('theme-transitioning');
      body.classList.remove('theme-transitioning');
    };

    if (hasThemeMountedRef.current) {
      const transitionToken = themeTransitionTokenRef.current + 1;
      const themeTransitionCleanupDeadline = Date.now() + THEME_TRANSITION_FALLBACK_MS;
      themeTransitionTokenRef.current = transitionToken;
      const scheduleThemeTransitionCleanup = (delay) => {
        const remaining = Math.max(0, themeTransitionCleanupDeadline - Date.now());
        const timeoutDelay = Math.min(delay, remaining);

        window.clearTimeout(themeTransitionTimerRef.current);
        themeTransitionTimerRef.current = window.setTimeout(() => {
          if (themeTransitionTokenRef.current !== transitionToken) {
            return;
          }

          clearThemeTransitionListeners();
          clearThemeTransitionClasses();
        }, timeoutDelay);
      };

      root.classList.add('theme-transitioning');
      body.classList.add('theme-transitioning');
      clearThemeTransitionListeners();

      const handleThemeTransitionEvent = (event) => {
        if (themeTransitionTokenRef.current !== transitionToken) {
          return;
        }

        if (!(event.target instanceof Element)) {
          return;
        }

        if (!THEME_TRANSITION_PROPERTIES.includes(event.propertyName)) {
          return;
        }

        if (!root.contains(event.target)) {
          return;
        }

        scheduleThemeTransitionCleanup(THEME_TRANSITION_SETTLE_MS);
      };

      themeTransitionEventHandlerRef.current = handleThemeTransitionEvent;
      document.addEventListener('transitioncancel', handleThemeTransitionEvent, true);
      document.addEventListener('transitionend', handleThemeTransitionEvent, true);
      scheduleThemeTransitionCleanup(THEME_TRANSITION_FALLBACK_MS);
    } else {
      hasThemeMountedRef.current = true;
    }

    root.dataset.theme = theme;
    body.dataset.theme = theme;
  }, [theme]);

  useEffect(() => () => {
    window.clearTimeout(themeTransitionTimerRef.current);
    clearThemeTransitionListeners();
    document.documentElement.classList.remove('theme-transitioning');
    document.body.classList.remove('theme-transitioning');
  }, []);

  const value = useMemo(() => {
    const localeOption = LOCALE_OPTIONS.find(option => option.code === locale) || LOCALE_OPTIONS[0];

    return {
      locale,
      setLocale,
      localeOptions: LOCALE_OPTIONS,
      localeLabel: localeOption.label,
      theme,
      setTheme,
      toggleTheme: () => setTheme(current => (current === 'dark' ? 'light' : 'dark')),
      t,
      formatDate,
      formatNumber,
      formatRelativeTime,
    };
  }, [formatDate, formatNumber, formatRelativeTime, locale, t, theme]);

  return <AppShellContext.Provider value={value}>{children}</AppShellContext.Provider>;
}

export function useAppShell() {
  const context = useContext(AppShellContext);
  if (!context) {
    throw new Error('useAppShell must be used within AppShellProvider');
  }

  return context;
}
